### ISSUE TITLE
Version 4: Apprise for notifications - feedback wanted!

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/node-toogoodtogo-watcher#215]
With version 4 I implemented [Apprise](https://github.com/caronc/apprise) support.
The idea is that users will run an Apprise Docker container and use Apprise to notify any of the many services that Apprise supports.

Considerations:
1. I cannot maintain all the notification integrations that people would want.
2. With this change we get an enormous amount of supported notification integrations at once.
3. The notification integrations are well documented.
4. The downside is the extra complexity cost for the user.

I need help to test this and possibly improve some things.
Please try to use it with the some notification services that you have / like, and report your findings.

Command for starting the apprise container:
```
docker run -rm --name apprise -p 8000:8000 -d caronc/apprise:latest
```

If you run with docker-compose add it to the docker-compose.yaml instead.
The host will be the container name 'apprise' if you run it in the same network as the watcher.
The host will be 'localhost' if you run the watcher outside a container via Node.

Documentation is still missing, we can add that later when we know that things are working properly.

**Comment by marklagendijk** [comment]
I just tested it with MQTT as shown above and that works.

**Comment by marklagendijk** [comment]
Added some documentation and added logging to Apprise implementation: `4.0.1`.

**Comment by zeus24** [comment]
Hi,
is it possible, that something with the normal telegram notification got broken? When a store increases the stock I get a telegram a notification with a list of all stores I am watching, instead of only the store with the increases stock.
On the top there is the store with the increases bags and all the other stores have a "0".

**Comment by marklagendijk** [comment]
@zeus24 yes. Fixed in `4.0.2`.

**Comment by zeus24** [comment]
Thanks solved, but now I found another bug. It seems the watcher has a problem, if a store only has a stock of "1". I just got 15 notifications for the same store and bags.  The notifications were sent every 2 minutes and they don't stop, although it is already sold :-(

**Comment by marklagendijk** [comment]
@zeus24 you probably messed up your `messageFilter` config, it determines when messages are sent. The defaults are to only send when the stock increases from 0 to another value:
```json
  "messageFilter": {
    "showUnchanged": false,
    "showDecrease": false,
    "showDecreaseToZero": false,
    "showIncrease": false,
    "showIncreaseFromZero": true
  }
```

**Comment by marklagendijk** [comment]
The idea of Docker is that every container lives it its own little world.
So whenever you want a container to access something from the host you have to bridge it in one way, or another.
In this case you can do that by mounting dbus as a volume:

```yaml
  apprise:
    image: caronc/apprise:latest
    volumes:
      - /var/run/dbus:/var/run/dbus
```

**Comment by Jolpar** [comment]
Thanks for the answer. It still doesn't work. I also tried different volumes (like /run/user/1000/bus), based on some comments here and there... That's not so important anyway.

**Comment by marklagendijk** [comment]
Might be a rights issue (caused by AppArmor or SELinux). You could try to verify that by running the container in privileged mode.
```yaml
  apprise:
    image: caronc/apprise:latest
    privileged: true
```

**Comment by Mcgive2003** [comment]
hello
Apprise it 's good idea.
i try to notification apprise with  IFTT it's good but no link in the notifications.
i try text and html  .
thanks for your job!

**Comment by Staubgeborener** [comment]
Maybe you can help me to use apprise correctly in docker.

This is my `docker-compose.yml`:
```yaml
version: "3"
services:
  toogoodtogo-watcher:
    image: marklagendijk/toogoodtogo-watcher
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./toogoodtogo-watcher:/home/node/.config/toogoodtogo-watcher-nodejs
  
  # This will make Apprise reachable on apprise:8080 for the other Docker Compose containers
  apprise:
    image: caronc/apprise:latest
  # Enable these to make Apprise reachable from outside Docker
    ports: 
       - "8085:8080"
```

As you can see, i need to use the host port `8085` (`8080` is already used on my host).

The config.json is also very basic:

```
                "apprise": {
                        "enabled": true,
                        "host": "apprise:8080",
                        "services": [
                                {
                                        "url": "tgram://token/chatid",
                                        "format": "text"
                                }
                        ]
                }
```

Can `apprise` now communicate with `node-toogoodtogo-watcher` over some internal docker port `8080` or do i need to add instead `8085` in the `config.json` file because they communicate somehow outside the container?
